### PR TITLE
Simplify K definitions

### PR DESCRIPTION
**Pull request by tothtamas28**
* Remove `calls.k`: can be integrated later with a corresponding target
* Replace `variables.k` by `calc.k`: defines sort `Stmt`, no need to redefine variable rules that way 
* Rename files an modules: shorter names
* Simplify `EXPR-SYNTAX`: reduce the number of concepts to be explained during a demo
* Add target `imp-semantics.expr`

### CODE REVIEW

**Comment by tothtamas28** [comment]
> The modules were split , with some repetition, in order to get a good course progression in a tutorial. It enables talking about only some of the concepts isolated in their individual file and running an exercise on that ifle without giving out too much unknown other code .

I did this refactoring in preparation of a tutorial I made last week. I tried to keep modularity, but wanted to reduce the number of unintuitive concepts to be explained (i.e. make K look user friendly). In particular, I inlined `VARIABLES` for the following reasons:
- The semantic rule for variable lookup had be repeated in `STATEMENTS` anyways, which is not really modular.
- The `let` rule does not seem to be correct (but I might be wrong),

So the course progression can still be:
1. Create an expression language
2. Create a "programming language" with only assignments and sequential statements
3. Extend the programming language with control structures

**Review by jberthold — DISMISSED** [review]
After discussing this, maybe we merge your new structure and the next person holding a tutorial can again modify it.
Or you re-instate the intermediate step without statements as a file?

**Comment by tothtamas28** [comment]
> Or you re-instate the intermediate step without statements as a file?

I added an intermediate definition `calc.k` that defines assignment and variable rules. `imp.k` then extends this language with control structures.

Does this variant enable the course progression you have in mind? If not, I'll restore the original module structure.

**Review by jberthold — APPROVED** [review]

**Comment by jberthold** [comment]
> Does this variant enable the course progression you have in mind? If not, I'll restore the original module structure.

Yes, that works, thank you!

BTW We could collect links to tutorial slides in the repo itself if you think this is useful. https://docs.google.com/presentation/d/1mx34lFnJ8niRPM7flcV_0sdSZ81BaTUV4YhiAacnbAY/edit#slide=id.p

**Pull request merged**
